defmodule Still.Release do
  @moduledoc """
  Release tasks for running without Mix installed. Invoked from the release
  binary via `bin/still eval "Still.Release.<task>()"` — typically from the
  install script during bootstrap, or by an operator running migrations.

  These functions are exercised by the install script and by manual
  operator commands — not by the unit test suite, which doesn't run
  against a built release.
  """

  alias Still.Audit.Actor

  @app :still

  # six:ignore:start

  @doc """
  Runs all pending migrations against every configured Ecto repo. Safe to
  invoke on every boot — idempotent.
  """
  def migrate do
    load_app()

    for repo <- repos() do
      {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :up, all: true))
    end
  end

  @doc """
  Rolls back one repo to the specified version.
  """
  def rollback(repo, version) when is_atom(repo) and is_integer(version) do
    load_app()
    {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :down, to: version))
  end

  @doc """
  Creates the first admin user during install-time bootstrap. Reads email,
  name, and password from environment variables so the install script can
  pipe them in without exposing them on the command line. Refuses to run
  if any users already exist — use the API to create additional users
  after bootstrap.

  Required environment variables:

    * `STILL_ADMIN_EMAIL`
    * `STILL_ADMIN_PASSWORD`
    * `STILL_ADMIN_NAME` (optional, defaults to `"admin"`)
  """
  def create_admin_user do
    load_app()

    {:ok, _, _} =
      Ecto.Migrator.with_repo(Still.Repo, fn _repo ->
        if Still.Accounts.has_users?() do
          raise "refusing to create admin user: at least one user already exists"
        end

        email = fetch_env!("STILL_ADMIN_EMAIL")
        password = fetch_env!("STILL_ADMIN_PASSWORD")
        name = System.get_env("STILL_ADMIN_NAME") || "admin"

        case Still.Accounts.create_user(Actor.system(), %{
               email: email,
               name: name,
               password: password,
               role: :admin
             }) do
          {:ok, user} ->
            # CLI/API-only path: hand back a long-lived admin API key so the
            # operator can script against the API immediately. The dashboard's
            # HTTP bootstrap returns a session token instead — different
            # consumer, different credential.
            {:ok, api_key} =
              Still.Accounts.create_api_key(Actor.system(), user, %{
                name: "bootstrap",
                permissions: ["admin"]
              })

            IO.puts("Created admin user: #{user.email}")
            IO.puts("Admin API key (shown once — save it): #{api_key.raw_key}")
            user

          {:error, changeset} ->
            raise "failed to create admin user: #{inspect(changeset.errors)}"
        end
      end)
  end

  @doc """
  Reconciles Caddy's base configuration. Called by the installer during
  fresh installs and upgrades; owns its own HTTP-client deps (`:req` and
  transitively `:finch` / `:telemetry`) so `install.sh` doesn't need to
  know.
  """
  def caddy_reconcile(opts) when is_list(opts) do
    load_app()
    {:ok, _} = Application.ensure_all_started(:req)

    case Still.CaddyBootstrap.reconcile(opts) do
      :ok ->
        :ok

      {:error, reason} ->
        IO.puts(:stderr, "Still.CaddyBootstrap.reconcile failed: #{inspect(reason)}")
        System.halt(1)
    end
  end

  @doc """
  Registers the local host in the `servers` table for single-server and
  controller-mode installs. Reads the stable server id from
  `STILL_SERVER_ID` (generated by the install script into
  `/etc/still/server.id`) and derives roles from `STILL_MODE`.

  Idempotent: if a server already exists at that id its row is left alone,
  so operator edits via the API survive installer re-runs.
  """
  def ensure_local_server do
    load_app()
    ensure_pubsub_started()

    {:ok, _, _} =
      Ecto.Migrator.with_repo(Still.Repo, fn _repo ->
        server_id = fetch_env!("STILL_SERVER_ID")
        host = fetch_env!("STILL_NODE_HOST")
        mode = System.get_env("STILL_MODE", "standalone")
        name = System.get_env("STILL_SERVER_NAME") || hostname()

        attrs = %{
          id: server_id,
          name: name,
          host: host,
          roles: roles_for_mode(mode)
        }

        case Still.Fleet.ensure_server(Actor.system(), attrs) do
          {:ok, server} ->
            IO.puts("Local server registered: #{server.name} (#{server.id})")
            server

          {:error, changeset} ->
            raise "failed to register local server: #{inspect(changeset.errors)}"
        end
      end)
  end

  defp roles_for_mode("standalone"), do: ["controller", "ingress", "application"]
  defp roles_for_mode("controller"), do: ["controller", "ingress"]

  defp roles_for_mode(other) do
    raise "ensure_local_server does not apply for STILL_MODE=#{inspect(other)}"
  end

  defp hostname do
    case :inet.gethostname() do
      {:ok, charlist} -> to_string(charlist)
      _ -> "localhost"
    end
  end

  defp fetch_env!(name) do
    System.get_env(name) || raise "#{name} environment variable is required"
  end

  defp repos do
    Application.fetch_env!(@app, :ecto_repos)
  end

  defp load_app do
    Application.ensure_all_started(:ssl)
    Application.ensure_loaded(@app)
  end

  # Install-time code paths broadcast on Still.PubSub (e.g. Fleet.ensure_server
  # taps the IngressReconciler). `still eval` runs in a fresh BEAM where the
  # full supervision tree isn't up, so PubSub has to be started explicitly.
  defp ensure_pubsub_started do
    case Process.whereis(Still.PubSub) do
      nil ->
        {:ok, _} = Application.ensure_all_started(:phoenix_pubsub)

        {:ok, _} =
          Supervisor.start_link(
            [{Phoenix.PubSub, name: Still.PubSub}],
            strategy: :one_for_one
          )

        :ok

      _pid ->
        :ok
    end
  end

  # six:ignore:stop
end
